# Generated by Django 4.0.3 on 2022-03-24 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_pandatoy'),
    ]

    operations = [
        migrations.AddField(
            model_name='panda',
            name='pandatoys',
            field=models.ManyToManyField(to='main_app.pandatoy'),
        ),
    ]
