# Generated by Django 4.0.3 on 2022-03-26 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_panda_pandatoys'),
    ]

    operations = [
        migrations.CreateModel(
            name='PandaSnack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('energy_increase', models.IntegerField()),
            ],
        ),
    ]
