# Generated by Django 4.0.3 on 2022-03-26 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_pandasnack'),
    ]

    operations = [
        migrations.AddField(
            model_name='panda',
            name='pandasnacks',
            field=models.ManyToManyField(to='main_app.pandasnack'),
        ),
    ]
